export enum BrandEnum {
    "lorenz" = "lorenz",
    "nissin" = "nissin",
    "papadopoulos" = "papadopoulos",
    "chupachups" = "chupa-chups",
    "kambly" = "kambly",
    "finnCrisp" = "finn crisp",
    "krisprolls" = "krisprolls",
    "7days" = "7days",
    "daim" = "daim",
    "bornier" = "bornier",
    "ranchera" = "ranchera",
    "3toques" = "3toques",
    "chefgourmet" = "chefgourmet",
    "ferrero" = "ferrero",
    "jordans" = "jordans",
    "remia" = "remia",
    "konecke" = "konecke",
    "fonzies" = "fonzies",
    "Iggy's" = "Iggy's",
    "iggy's" = "iggy's",
    "jacobs" = "jacobs",
    "brickcity" = "brickcity",
    "mazzetti" = "mazzetti",
    "appel" = "appel",
    "crown" = "crown",
    "muhlhauser" = "muhlhauser"
}
